// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: janusgraph/v1/graph_manager.proto

package org.janusgraph.graphdb.grpc;

/**
 * Protobuf type {@code janusgraph.v1.GetJanusGraphContextsResponse}
 */
public final class GetJanusGraphContextsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:janusgraph.v1.GetJanusGraphContextsResponse)
    GetJanusGraphContextsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetJanusGraphContextsResponse.newBuilder() to construct.
  private GetJanusGraphContextsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetJanusGraphContextsResponse() {
    contexts_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetJanusGraphContextsResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetJanusGraphContextsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              contexts_ = new java.util.ArrayList<org.janusgraph.graphdb.grpc.types.JanusGraphContext>();
              mutable_bitField0_ |= 0x00000001;
            }
            contexts_.add(
                input.readMessage(org.janusgraph.graphdb.grpc.types.JanusGraphContext.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        contexts_ = java.util.Collections.unmodifiableList(contexts_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.janusgraph.graphdb.grpc.GraphManagerService.internal_static_janusgraph_v1_GetJanusGraphContextsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.janusgraph.graphdb.grpc.GraphManagerService.internal_static_janusgraph_v1_GetJanusGraphContextsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse.class, org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse.Builder.class);
  }

  public static final int CONTEXTS_FIELD_NUMBER = 1;
  private java.util.List<org.janusgraph.graphdb.grpc.types.JanusGraphContext> contexts_;
  /**
   * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
   */
  @java.lang.Override
  public java.util.List<org.janusgraph.graphdb.grpc.types.JanusGraphContext> getContextsList() {
    return contexts_;
  }
  /**
   * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.janusgraph.graphdb.grpc.types.JanusGraphContextOrBuilder> 
      getContextsOrBuilderList() {
    return contexts_;
  }
  /**
   * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
   */
  @java.lang.Override
  public int getContextsCount() {
    return contexts_.size();
  }
  /**
   * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
   */
  @java.lang.Override
  public org.janusgraph.graphdb.grpc.types.JanusGraphContext getContexts(int index) {
    return contexts_.get(index);
  }
  /**
   * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
   */
  @java.lang.Override
  public org.janusgraph.graphdb.grpc.types.JanusGraphContextOrBuilder getContextsOrBuilder(
      int index) {
    return contexts_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < contexts_.size(); i++) {
      output.writeMessage(1, contexts_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < contexts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, contexts_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse)) {
      return super.equals(obj);
    }
    org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse other = (org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse) obj;

    if (!getContextsList()
        .equals(other.getContextsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getContextsCount() > 0) {
      hash = (37 * hash) + CONTEXTS_FIELD_NUMBER;
      hash = (53 * hash) + getContextsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code janusgraph.v1.GetJanusGraphContextsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:janusgraph.v1.GetJanusGraphContextsResponse)
      org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.janusgraph.graphdb.grpc.GraphManagerService.internal_static_janusgraph_v1_GetJanusGraphContextsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.janusgraph.graphdb.grpc.GraphManagerService.internal_static_janusgraph_v1_GetJanusGraphContextsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse.class, org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse.Builder.class);
    }

    // Construct using org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getContextsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (contextsBuilder_ == null) {
        contexts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        contextsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.janusgraph.graphdb.grpc.GraphManagerService.internal_static_janusgraph_v1_GetJanusGraphContextsResponse_descriptor;
    }

    @java.lang.Override
    public org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse getDefaultInstanceForType() {
      return org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse build() {
      org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse buildPartial() {
      org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse result = new org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse(this);
      int from_bitField0_ = bitField0_;
      if (contextsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          contexts_ = java.util.Collections.unmodifiableList(contexts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.contexts_ = contexts_;
      } else {
        result.contexts_ = contextsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse) {
        return mergeFrom((org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse other) {
      if (other == org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse.getDefaultInstance()) return this;
      if (contextsBuilder_ == null) {
        if (!other.contexts_.isEmpty()) {
          if (contexts_.isEmpty()) {
            contexts_ = other.contexts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureContextsIsMutable();
            contexts_.addAll(other.contexts_);
          }
          onChanged();
        }
      } else {
        if (!other.contexts_.isEmpty()) {
          if (contextsBuilder_.isEmpty()) {
            contextsBuilder_.dispose();
            contextsBuilder_ = null;
            contexts_ = other.contexts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            contextsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getContextsFieldBuilder() : null;
          } else {
            contextsBuilder_.addAllMessages(other.contexts_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.janusgraph.graphdb.grpc.types.JanusGraphContext> contexts_ =
      java.util.Collections.emptyList();
    private void ensureContextsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        contexts_ = new java.util.ArrayList<org.janusgraph.graphdb.grpc.types.JanusGraphContext>(contexts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.janusgraph.graphdb.grpc.types.JanusGraphContext, org.janusgraph.graphdb.grpc.types.JanusGraphContext.Builder, org.janusgraph.graphdb.grpc.types.JanusGraphContextOrBuilder> contextsBuilder_;

    /**
     * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
     */
    public java.util.List<org.janusgraph.graphdb.grpc.types.JanusGraphContext> getContextsList() {
      if (contextsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(contexts_);
      } else {
        return contextsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
     */
    public int getContextsCount() {
      if (contextsBuilder_ == null) {
        return contexts_.size();
      } else {
        return contextsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
     */
    public org.janusgraph.graphdb.grpc.types.JanusGraphContext getContexts(int index) {
      if (contextsBuilder_ == null) {
        return contexts_.get(index);
      } else {
        return contextsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
     */
    public Builder setContexts(
        int index, org.janusgraph.graphdb.grpc.types.JanusGraphContext value) {
      if (contextsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContextsIsMutable();
        contexts_.set(index, value);
        onChanged();
      } else {
        contextsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
     */
    public Builder setContexts(
        int index, org.janusgraph.graphdb.grpc.types.JanusGraphContext.Builder builderForValue) {
      if (contextsBuilder_ == null) {
        ensureContextsIsMutable();
        contexts_.set(index, builderForValue.build());
        onChanged();
      } else {
        contextsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
     */
    public Builder addContexts(org.janusgraph.graphdb.grpc.types.JanusGraphContext value) {
      if (contextsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContextsIsMutable();
        contexts_.add(value);
        onChanged();
      } else {
        contextsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
     */
    public Builder addContexts(
        int index, org.janusgraph.graphdb.grpc.types.JanusGraphContext value) {
      if (contextsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContextsIsMutable();
        contexts_.add(index, value);
        onChanged();
      } else {
        contextsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
     */
    public Builder addContexts(
        org.janusgraph.graphdb.grpc.types.JanusGraphContext.Builder builderForValue) {
      if (contextsBuilder_ == null) {
        ensureContextsIsMutable();
        contexts_.add(builderForValue.build());
        onChanged();
      } else {
        contextsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
     */
    public Builder addContexts(
        int index, org.janusgraph.graphdb.grpc.types.JanusGraphContext.Builder builderForValue) {
      if (contextsBuilder_ == null) {
        ensureContextsIsMutable();
        contexts_.add(index, builderForValue.build());
        onChanged();
      } else {
        contextsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
     */
    public Builder addAllContexts(
        java.lang.Iterable<? extends org.janusgraph.graphdb.grpc.types.JanusGraphContext> values) {
      if (contextsBuilder_ == null) {
        ensureContextsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, contexts_);
        onChanged();
      } else {
        contextsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
     */
    public Builder clearContexts() {
      if (contextsBuilder_ == null) {
        contexts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        contextsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
     */
    public Builder removeContexts(int index) {
      if (contextsBuilder_ == null) {
        ensureContextsIsMutable();
        contexts_.remove(index);
        onChanged();
      } else {
        contextsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
     */
    public org.janusgraph.graphdb.grpc.types.JanusGraphContext.Builder getContextsBuilder(
        int index) {
      return getContextsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
     */
    public org.janusgraph.graphdb.grpc.types.JanusGraphContextOrBuilder getContextsOrBuilder(
        int index) {
      if (contextsBuilder_ == null) {
        return contexts_.get(index);  } else {
        return contextsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
     */
    public java.util.List<? extends org.janusgraph.graphdb.grpc.types.JanusGraphContextOrBuilder> 
         getContextsOrBuilderList() {
      if (contextsBuilder_ != null) {
        return contextsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(contexts_);
      }
    }
    /**
     * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
     */
    public org.janusgraph.graphdb.grpc.types.JanusGraphContext.Builder addContextsBuilder() {
      return getContextsFieldBuilder().addBuilder(
          org.janusgraph.graphdb.grpc.types.JanusGraphContext.getDefaultInstance());
    }
    /**
     * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
     */
    public org.janusgraph.graphdb.grpc.types.JanusGraphContext.Builder addContextsBuilder(
        int index) {
      return getContextsFieldBuilder().addBuilder(
          index, org.janusgraph.graphdb.grpc.types.JanusGraphContext.getDefaultInstance());
    }
    /**
     * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
     */
    public java.util.List<org.janusgraph.graphdb.grpc.types.JanusGraphContext.Builder> 
         getContextsBuilderList() {
      return getContextsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.janusgraph.graphdb.grpc.types.JanusGraphContext, org.janusgraph.graphdb.grpc.types.JanusGraphContext.Builder, org.janusgraph.graphdb.grpc.types.JanusGraphContextOrBuilder> 
        getContextsFieldBuilder() {
      if (contextsBuilder_ == null) {
        contextsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.janusgraph.graphdb.grpc.types.JanusGraphContext, org.janusgraph.graphdb.grpc.types.JanusGraphContext.Builder, org.janusgraph.graphdb.grpc.types.JanusGraphContextOrBuilder>(
                contexts_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        contexts_ = null;
      }
      return contextsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:janusgraph.v1.GetJanusGraphContextsResponse)
  }

  // @@protoc_insertion_point(class_scope:janusgraph.v1.GetJanusGraphContextsResponse)
  private static final org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse();
  }

  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetJanusGraphContextsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetJanusGraphContextsResponse>() {
    @java.lang.Override
    public GetJanusGraphContextsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetJanusGraphContextsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetJanusGraphContextsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetJanusGraphContextsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.janusgraph.graphdb.grpc.GetJanusGraphContextsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

