// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: janusgraph/v1/graph_manager.proto

package org.janusgraph.graphdb.grpc;

public interface GetJanusGraphContextsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:janusgraph.v1.GetJanusGraphContextsRequest)
    com.google.protobuf.MessageOrBuilder {
}
