// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: janusgraph/v1/graph_manager.proto

package org.janusgraph.graphdb.grpc;

/**
 * Protobuf type {@code janusgraph.v1.GetJanusGraphContextByGraphNameRequest}
 */
public final class GetJanusGraphContextByGraphNameRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:janusgraph.v1.GetJanusGraphContextByGraphNameRequest)
    GetJanusGraphContextByGraphNameRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetJanusGraphContextByGraphNameRequest.newBuilder() to construct.
  private GetJanusGraphContextByGraphNameRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetJanusGraphContextByGraphNameRequest() {
    graphName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetJanusGraphContextByGraphNameRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetJanusGraphContextByGraphNameRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            graphName_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.janusgraph.graphdb.grpc.GraphManagerService.internal_static_janusgraph_v1_GetJanusGraphContextByGraphNameRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.janusgraph.graphdb.grpc.GraphManagerService.internal_static_janusgraph_v1_GetJanusGraphContextByGraphNameRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest.class, org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest.Builder.class);
  }

  public static final int GRAPH_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object graphName_;
  /**
   * <code>string graph_name = 1 [json_name = "graphName"];</code>
   * @return The graphName.
   */
  @java.lang.Override
  public java.lang.String getGraphName() {
    java.lang.Object ref = graphName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      graphName_ = s;
      return s;
    }
  }
  /**
   * <code>string graph_name = 1 [json_name = "graphName"];</code>
   * @return The bytes for graphName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGraphNameBytes() {
    java.lang.Object ref = graphName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      graphName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getGraphNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, graphName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getGraphNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, graphName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest)) {
      return super.equals(obj);
    }
    org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest other = (org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest) obj;

    if (!getGraphName()
        .equals(other.getGraphName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GRAPH_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getGraphName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code janusgraph.v1.GetJanusGraphContextByGraphNameRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:janusgraph.v1.GetJanusGraphContextByGraphNameRequest)
      org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.janusgraph.graphdb.grpc.GraphManagerService.internal_static_janusgraph_v1_GetJanusGraphContextByGraphNameRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.janusgraph.graphdb.grpc.GraphManagerService.internal_static_janusgraph_v1_GetJanusGraphContextByGraphNameRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest.class, org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest.Builder.class);
    }

    // Construct using org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      graphName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.janusgraph.graphdb.grpc.GraphManagerService.internal_static_janusgraph_v1_GetJanusGraphContextByGraphNameRequest_descriptor;
    }

    @java.lang.Override
    public org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest getDefaultInstanceForType() {
      return org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest build() {
      org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest buildPartial() {
      org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest result = new org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest(this);
      result.graphName_ = graphName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest) {
        return mergeFrom((org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest other) {
      if (other == org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest.getDefaultInstance()) return this;
      if (!other.getGraphName().isEmpty()) {
        graphName_ = other.graphName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object graphName_ = "";
    /**
     * <code>string graph_name = 1 [json_name = "graphName"];</code>
     * @return The graphName.
     */
    public java.lang.String getGraphName() {
      java.lang.Object ref = graphName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        graphName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string graph_name = 1 [json_name = "graphName"];</code>
     * @return The bytes for graphName.
     */
    public com.google.protobuf.ByteString
        getGraphNameBytes() {
      java.lang.Object ref = graphName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        graphName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string graph_name = 1 [json_name = "graphName"];</code>
     * @param value The graphName to set.
     * @return This builder for chaining.
     */
    public Builder setGraphName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      graphName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string graph_name = 1 [json_name = "graphName"];</code>
     * @return This builder for chaining.
     */
    public Builder clearGraphName() {
      
      graphName_ = getDefaultInstance().getGraphName();
      onChanged();
      return this;
    }
    /**
     * <code>string graph_name = 1 [json_name = "graphName"];</code>
     * @param value The bytes for graphName to set.
     * @return This builder for chaining.
     */
    public Builder setGraphNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      graphName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:janusgraph.v1.GetJanusGraphContextByGraphNameRequest)
  }

  // @@protoc_insertion_point(class_scope:janusgraph.v1.GetJanusGraphContextByGraphNameRequest)
  private static final org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest();
  }

  public static org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetJanusGraphContextByGraphNameRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetJanusGraphContextByGraphNameRequest>() {
    @java.lang.Override
    public GetJanusGraphContextByGraphNameRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetJanusGraphContextByGraphNameRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetJanusGraphContextByGraphNameRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetJanusGraphContextByGraphNameRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.janusgraph.graphdb.grpc.GetJanusGraphContextByGraphNameRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

