// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: janusgraph/v1/graph_manager.proto

package org.janusgraph.graphdb.grpc;

public interface GetJanusGraphContextByGraphNameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:janusgraph.v1.GetJanusGraphContextByGraphNameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string graph_name = 1 [json_name = "graphName"];</code>
   * @return The graphName.
   */
  java.lang.String getGraphName();
  /**
   * <code>string graph_name = 1 [json_name = "graphName"];</code>
   * @return The bytes for graphName.
   */
  com.google.protobuf.ByteString
      getGraphNameBytes();
}
