// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: janusgraph/v1/graph_manager.proto

package org.janusgraph.graphdb.grpc;

public interface GetJanusGraphContextByGraphNameResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:janusgraph.v1.GetJanusGraphContextByGraphNameResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.janusgraph.types.v1.JanusGraphContext context = 1 [json_name = "context"];</code>
   * @return Whether the context field is set.
   */
  boolean hasContext();
  /**
   * <code>.janusgraph.types.v1.JanusGraphContext context = 1 [json_name = "context"];</code>
   * @return The context.
   */
  org.janusgraph.graphdb.grpc.types.JanusGraphContext getContext();
  /**
   * <code>.janusgraph.types.v1.JanusGraphContext context = 1 [json_name = "context"];</code>
   */
  org.janusgraph.graphdb.grpc.types.JanusGraphContextOrBuilder getContextOrBuilder();
}
