// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: janusgraph/v1/graph_manager.proto

package org.janusgraph.graphdb.grpc;

public interface GetJanusGraphContextsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:janusgraph.v1.GetJanusGraphContextsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
   */
  java.util.List<org.janusgraph.graphdb.grpc.types.JanusGraphContext> 
      getContextsList();
  /**
   * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
   */
  org.janusgraph.graphdb.grpc.types.JanusGraphContext getContexts(int index);
  /**
   * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
   */
  int getContextsCount();
  /**
   * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
   */
  java.util.List<? extends org.janusgraph.graphdb.grpc.types.JanusGraphContextOrBuilder> 
      getContextsOrBuilderList();
  /**
   * <code>repeated .janusgraph.types.v1.JanusGraphContext contexts = 1 [json_name = "contexts"];</code>
   */
  org.janusgraph.graphdb.grpc.types.JanusGraphContextOrBuilder getContextsOrBuilder(
      int index);
}
