// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: janusgraph/v1/graph_manager.proto

package org.janusgraph.graphdb.grpc;

public interface GetVersionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:janusgraph.v1.GetVersionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string janusgraph_version = 1 [json_name = "janusgraphVersion"];</code>
   * @return The janusgraphVersion.
   */
  java.lang.String getJanusgraphVersion();
  /**
   * <code>string janusgraph_version = 1 [json_name = "janusgraphVersion"];</code>
   * @return The bytes for janusgraphVersion.
   */
  com.google.protobuf.ByteString
      getJanusgraphVersionBytes();

  /**
   * <code>string tinkerpop_version = 2 [json_name = "tinkerpopVersion"];</code>
   * @return The tinkerpopVersion.
   */
  java.lang.String getTinkerpopVersion();
  /**
   * <code>string tinkerpop_version = 2 [json_name = "tinkerpopVersion"];</code>
   * @return The bytes for tinkerpopVersion.
   */
  com.google.protobuf.ByteString
      getTinkerpopVersionBytes();
}
