// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: janusgraph/v1/graph_manager.proto

package org.janusgraph.graphdb.grpc;

/**
 * Protobuf type {@code janusgraph.v1.GetVersionResponse}
 */
public final class GetVersionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:janusgraph.v1.GetVersionResponse)
    GetVersionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetVersionResponse.newBuilder() to construct.
  private GetVersionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetVersionResponse() {
    janusgraphVersion_ = "";
    tinkerpopVersion_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetVersionResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetVersionResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            janusgraphVersion_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            tinkerpopVersion_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.janusgraph.graphdb.grpc.GraphManagerService.internal_static_janusgraph_v1_GetVersionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.janusgraph.graphdb.grpc.GraphManagerService.internal_static_janusgraph_v1_GetVersionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.janusgraph.graphdb.grpc.GetVersionResponse.class, org.janusgraph.graphdb.grpc.GetVersionResponse.Builder.class);
  }

  public static final int JANUSGRAPH_VERSION_FIELD_NUMBER = 1;
  private volatile java.lang.Object janusgraphVersion_;
  /**
   * <code>string janusgraph_version = 1 [json_name = "janusgraphVersion"];</code>
   * @return The janusgraphVersion.
   */
  @java.lang.Override
  public java.lang.String getJanusgraphVersion() {
    java.lang.Object ref = janusgraphVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      janusgraphVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string janusgraph_version = 1 [json_name = "janusgraphVersion"];</code>
   * @return The bytes for janusgraphVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJanusgraphVersionBytes() {
    java.lang.Object ref = janusgraphVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      janusgraphVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TINKERPOP_VERSION_FIELD_NUMBER = 2;
  private volatile java.lang.Object tinkerpopVersion_;
  /**
   * <code>string tinkerpop_version = 2 [json_name = "tinkerpopVersion"];</code>
   * @return The tinkerpopVersion.
   */
  @java.lang.Override
  public java.lang.String getTinkerpopVersion() {
    java.lang.Object ref = tinkerpopVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tinkerpopVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string tinkerpop_version = 2 [json_name = "tinkerpopVersion"];</code>
   * @return The bytes for tinkerpopVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTinkerpopVersionBytes() {
    java.lang.Object ref = tinkerpopVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tinkerpopVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getJanusgraphVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, janusgraphVersion_);
    }
    if (!getTinkerpopVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tinkerpopVersion_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getJanusgraphVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, janusgraphVersion_);
    }
    if (!getTinkerpopVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tinkerpopVersion_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.janusgraph.graphdb.grpc.GetVersionResponse)) {
      return super.equals(obj);
    }
    org.janusgraph.graphdb.grpc.GetVersionResponse other = (org.janusgraph.graphdb.grpc.GetVersionResponse) obj;

    if (!getJanusgraphVersion()
        .equals(other.getJanusgraphVersion())) return false;
    if (!getTinkerpopVersion()
        .equals(other.getTinkerpopVersion())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + JANUSGRAPH_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getJanusgraphVersion().hashCode();
    hash = (37 * hash) + TINKERPOP_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getTinkerpopVersion().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.janusgraph.graphdb.grpc.GetVersionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.janusgraph.graphdb.grpc.GetVersionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.GetVersionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.janusgraph.graphdb.grpc.GetVersionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.GetVersionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.janusgraph.graphdb.grpc.GetVersionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.GetVersionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.janusgraph.graphdb.grpc.GetVersionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.GetVersionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.janusgraph.graphdb.grpc.GetVersionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.GetVersionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.janusgraph.graphdb.grpc.GetVersionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.janusgraph.graphdb.grpc.GetVersionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code janusgraph.v1.GetVersionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:janusgraph.v1.GetVersionResponse)
      org.janusgraph.graphdb.grpc.GetVersionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.janusgraph.graphdb.grpc.GraphManagerService.internal_static_janusgraph_v1_GetVersionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.janusgraph.graphdb.grpc.GraphManagerService.internal_static_janusgraph_v1_GetVersionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.janusgraph.graphdb.grpc.GetVersionResponse.class, org.janusgraph.graphdb.grpc.GetVersionResponse.Builder.class);
    }

    // Construct using org.janusgraph.graphdb.grpc.GetVersionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      janusgraphVersion_ = "";

      tinkerpopVersion_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.janusgraph.graphdb.grpc.GraphManagerService.internal_static_janusgraph_v1_GetVersionResponse_descriptor;
    }

    @java.lang.Override
    public org.janusgraph.graphdb.grpc.GetVersionResponse getDefaultInstanceForType() {
      return org.janusgraph.graphdb.grpc.GetVersionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.janusgraph.graphdb.grpc.GetVersionResponse build() {
      org.janusgraph.graphdb.grpc.GetVersionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.janusgraph.graphdb.grpc.GetVersionResponse buildPartial() {
      org.janusgraph.graphdb.grpc.GetVersionResponse result = new org.janusgraph.graphdb.grpc.GetVersionResponse(this);
      result.janusgraphVersion_ = janusgraphVersion_;
      result.tinkerpopVersion_ = tinkerpopVersion_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.janusgraph.graphdb.grpc.GetVersionResponse) {
        return mergeFrom((org.janusgraph.graphdb.grpc.GetVersionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.janusgraph.graphdb.grpc.GetVersionResponse other) {
      if (other == org.janusgraph.graphdb.grpc.GetVersionResponse.getDefaultInstance()) return this;
      if (!other.getJanusgraphVersion().isEmpty()) {
        janusgraphVersion_ = other.janusgraphVersion_;
        onChanged();
      }
      if (!other.getTinkerpopVersion().isEmpty()) {
        tinkerpopVersion_ = other.tinkerpopVersion_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.janusgraph.graphdb.grpc.GetVersionResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.janusgraph.graphdb.grpc.GetVersionResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object janusgraphVersion_ = "";
    /**
     * <code>string janusgraph_version = 1 [json_name = "janusgraphVersion"];</code>
     * @return The janusgraphVersion.
     */
    public java.lang.String getJanusgraphVersion() {
      java.lang.Object ref = janusgraphVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        janusgraphVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string janusgraph_version = 1 [json_name = "janusgraphVersion"];</code>
     * @return The bytes for janusgraphVersion.
     */
    public com.google.protobuf.ByteString
        getJanusgraphVersionBytes() {
      java.lang.Object ref = janusgraphVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        janusgraphVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string janusgraph_version = 1 [json_name = "janusgraphVersion"];</code>
     * @param value The janusgraphVersion to set.
     * @return This builder for chaining.
     */
    public Builder setJanusgraphVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      janusgraphVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string janusgraph_version = 1 [json_name = "janusgraphVersion"];</code>
     * @return This builder for chaining.
     */
    public Builder clearJanusgraphVersion() {
      
      janusgraphVersion_ = getDefaultInstance().getJanusgraphVersion();
      onChanged();
      return this;
    }
    /**
     * <code>string janusgraph_version = 1 [json_name = "janusgraphVersion"];</code>
     * @param value The bytes for janusgraphVersion to set.
     * @return This builder for chaining.
     */
    public Builder setJanusgraphVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      janusgraphVersion_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tinkerpopVersion_ = "";
    /**
     * <code>string tinkerpop_version = 2 [json_name = "tinkerpopVersion"];</code>
     * @return The tinkerpopVersion.
     */
    public java.lang.String getTinkerpopVersion() {
      java.lang.Object ref = tinkerpopVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tinkerpopVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tinkerpop_version = 2 [json_name = "tinkerpopVersion"];</code>
     * @return The bytes for tinkerpopVersion.
     */
    public com.google.protobuf.ByteString
        getTinkerpopVersionBytes() {
      java.lang.Object ref = tinkerpopVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tinkerpopVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tinkerpop_version = 2 [json_name = "tinkerpopVersion"];</code>
     * @param value The tinkerpopVersion to set.
     * @return This builder for chaining.
     */
    public Builder setTinkerpopVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tinkerpopVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tinkerpop_version = 2 [json_name = "tinkerpopVersion"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTinkerpopVersion() {
      
      tinkerpopVersion_ = getDefaultInstance().getTinkerpopVersion();
      onChanged();
      return this;
    }
    /**
     * <code>string tinkerpop_version = 2 [json_name = "tinkerpopVersion"];</code>
     * @param value The bytes for tinkerpopVersion to set.
     * @return This builder for chaining.
     */
    public Builder setTinkerpopVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tinkerpopVersion_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:janusgraph.v1.GetVersionResponse)
  }

  // @@protoc_insertion_point(class_scope:janusgraph.v1.GetVersionResponse)
  private static final org.janusgraph.graphdb.grpc.GetVersionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.janusgraph.graphdb.grpc.GetVersionResponse();
  }

  public static org.janusgraph.graphdb.grpc.GetVersionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetVersionResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetVersionResponse>() {
    @java.lang.Override
    public GetVersionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetVersionResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetVersionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetVersionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.janusgraph.graphdb.grpc.GetVersionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

