// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: janusgraph/v1/graph_manager.proto

package org.janusgraph.graphdb.grpc;

public final class GraphManagerService {
  private GraphManagerService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_janusgraph_v1_GetJanusGraphContextByGraphNameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_janusgraph_v1_GetJanusGraphContextByGraphNameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_janusgraph_v1_GetJanusGraphContextByGraphNameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_janusgraph_v1_GetJanusGraphContextByGraphNameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_janusgraph_v1_GetJanusGraphContextsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_janusgraph_v1_GetJanusGraphContextsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_janusgraph_v1_GetJanusGraphContextsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_janusgraph_v1_GetJanusGraphContextsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_janusgraph_v1_GetVersionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_janusgraph_v1_GetVersionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_janusgraph_v1_GetVersionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_janusgraph_v1_GetVersionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!janusgraph/v1/graph_manager.proto\022\rjan" +
      "usgraph.v1\032%janusgraph/types/v1/graph_ty" +
      "pes.proto\"k\n\'GetJanusGraphContextByGraph" +
      "NameResponse\022@\n\007context\030\001 \001(\0132&.janusgra" +
      "ph.types.v1.JanusGraphContextR\007context\"G" +
      "\n&GetJanusGraphContextByGraphNameRequest" +
      "\022\035\n\ngraph_name\030\001 \001(\tR\tgraphName\"c\n\035GetJa" +
      "nusGraphContextsResponse\022B\n\010contexts\030\001 \003" +
      "(\0132&.janusgraph.types.v1.JanusGraphConte" +
      "xtR\010contexts\"\036\n\034GetJanusGraphContextsReq" +
      "uest\"\023\n\021GetVersionRequest\"p\n\022GetVersionR" +
      "esponse\022-\n\022janusgraph_version\030\001 \001(\tR\021jan" +
      "usgraphVersion\022+\n\021tinkerpop_version\030\002 \001(" +
      "\tR\020tinkerpopVersion2\364\002\n\030JanusGraphManage" +
      "rService\022r\n\025GetJanusGraphContexts\022+.janu" +
      "sgraph.v1.GetJanusGraphContextsRequest\032," +
      ".janusgraph.v1.GetJanusGraphContextsResp" +
      "onse\022\220\001\n\037GetJanusGraphContextByGraphName" +
      "\0225.janusgraph.v1.GetJanusGraphContextByG" +
      "raphNameRequest\0326.janusgraph.v1.GetJanus" +
      "GraphContextByGraphNameResponse\022Q\n\nGetVe" +
      "rsion\022 .janusgraph.v1.GetVersionRequest\032" +
      "!.janusgraph.v1.GetVersionResponseB4\n\033or" +
      "g.janusgraph.graphdb.grpcB\023GraphManagerS" +
      "erviceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.janusgraph.graphdb.grpc.types.GraphTypes.getDescriptor(),
        });
    internal_static_janusgraph_v1_GetJanusGraphContextByGraphNameResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_janusgraph_v1_GetJanusGraphContextByGraphNameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_janusgraph_v1_GetJanusGraphContextByGraphNameResponse_descriptor,
        new java.lang.String[] { "Context", });
    internal_static_janusgraph_v1_GetJanusGraphContextByGraphNameRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_janusgraph_v1_GetJanusGraphContextByGraphNameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_janusgraph_v1_GetJanusGraphContextByGraphNameRequest_descriptor,
        new java.lang.String[] { "GraphName", });
    internal_static_janusgraph_v1_GetJanusGraphContextsResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_janusgraph_v1_GetJanusGraphContextsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_janusgraph_v1_GetJanusGraphContextsResponse_descriptor,
        new java.lang.String[] { "Contexts", });
    internal_static_janusgraph_v1_GetJanusGraphContextsRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_janusgraph_v1_GetJanusGraphContextsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_janusgraph_v1_GetJanusGraphContextsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_janusgraph_v1_GetVersionRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_janusgraph_v1_GetVersionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_janusgraph_v1_GetVersionRequest_descriptor,
        new java.lang.String[] { });
    internal_static_janusgraph_v1_GetVersionResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_janusgraph_v1_GetVersionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_janusgraph_v1_GetVersionResponse_descriptor,
        new java.lang.String[] { "JanusgraphVersion", "TinkerpopVersion", });
    org.janusgraph.graphdb.grpc.types.GraphTypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
