// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: janusgraph/types/v1/schema_types.proto

package org.janusgraph.graphdb.grpc.types;

/**
 * Protobuf type {@code janusgraph.types.v1.EdgeLabel}
 */
public final class EdgeLabel extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:janusgraph.types.v1.EdgeLabel)
    EdgeLabelOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EdgeLabel.newBuilder() to construct.
  private EdgeLabel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EdgeLabel() {
    name_ = "";
    direction_ = 0;
    multiplicity_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EdgeLabel();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EdgeLabel(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (id_ != null) {
              subBuilder = id_.toBuilder();
            }
            id_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(id_);
              id_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            direction_ = rawValue;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            multiplicity_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.janusgraph.graphdb.grpc.types.SchemaTypes.internal_static_janusgraph_types_v1_EdgeLabel_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.janusgraph.graphdb.grpc.types.SchemaTypes.internal_static_janusgraph_types_v1_EdgeLabel_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.janusgraph.graphdb.grpc.types.EdgeLabel.class, org.janusgraph.graphdb.grpc.types.EdgeLabel.Builder.class);
  }

  /**
   * Protobuf enum {@code janusgraph.types.v1.EdgeLabel.Direction}
   */
  public enum Direction
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Edge can be queried from both vertices.
     * </pre>
     *
     * <code>BOTH = 0;</code>
     */
    BOTH(0),
    /**
     * <pre>
     * Edge can be only queried from the outgoing vertex.
     * Direction OUT should be only used by experts, see https://docs.janusgraph.org/schema/advschema/#unidirected-edges.
     * </pre>
     *
     * <code>OUT = 1;</code>
     */
    OUT(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Edge can be queried from both vertices.
     * </pre>
     *
     * <code>BOTH = 0;</code>
     */
    public static final int BOTH_VALUE = 0;
    /**
     * <pre>
     * Edge can be only queried from the outgoing vertex.
     * Direction OUT should be only used by experts, see https://docs.janusgraph.org/schema/advschema/#unidirected-edges.
     * </pre>
     *
     * <code>OUT = 1;</code>
     */
    public static final int OUT_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Direction valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Direction forNumber(int value) {
      switch (value) {
        case 0: return BOTH;
        case 1: return OUT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Direction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Direction> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Direction>() {
            public Direction findValueByNumber(int number) {
              return Direction.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.janusgraph.graphdb.grpc.types.EdgeLabel.getDescriptor().getEnumTypes().get(0);
    }

    private static final Direction[] VALUES = values();

    public static Direction valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Direction(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:janusgraph.types.v1.EdgeLabel.Direction)
  }

  /**
   * Protobuf enum {@code janusgraph.types.v1.EdgeLabel.Multiplicity}
   */
  public enum Multiplicity
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * The given edge label specifies a multi-graph, meaning that the multiplicity is not constrained and that
     * there may be multiple edges of this label between any given pair of vertices.
     * </pre>
     *
     * <code>MULTI = 0;</code>
     */
    MULTI(0),
    /**
     * <pre>
     * The given edge label specifies a simple graph, meaning that the multiplicity is not constrained but that there
     * can only be at most a single edge of this label between a given pair of vertices.
     * </pre>
     *
     * <code>SIMPLE = 1;</code>
     */
    SIMPLE(1),
    /**
     * <pre>
     * There can only be a single in-edge of this label for a given vertex but multiple out-edges (i.e. in-unique).
     * </pre>
     *
     * <code>ONE2MANY = 2;</code>
     */
    ONE2MANY(2),
    /**
     * <pre>
     * There can only be a single out-edge of this label for a given vertex but multiple in-edges (i.e. out-unique).
     * </pre>
     *
     * <code>MANY2ONE = 3;</code>
     */
    MANY2ONE(3),
    /**
     * <pre>
     * There can be only a single in and out-edge of this label for a given vertex (i.e. unique in both directions).
     * </pre>
     *
     * <code>ONE2ONE = 4;</code>
     */
    ONE2ONE(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * The given edge label specifies a multi-graph, meaning that the multiplicity is not constrained and that
     * there may be multiple edges of this label between any given pair of vertices.
     * </pre>
     *
     * <code>MULTI = 0;</code>
     */
    public static final int MULTI_VALUE = 0;
    /**
     * <pre>
     * The given edge label specifies a simple graph, meaning that the multiplicity is not constrained but that there
     * can only be at most a single edge of this label between a given pair of vertices.
     * </pre>
     *
     * <code>SIMPLE = 1;</code>
     */
    public static final int SIMPLE_VALUE = 1;
    /**
     * <pre>
     * There can only be a single in-edge of this label for a given vertex but multiple out-edges (i.e. in-unique).
     * </pre>
     *
     * <code>ONE2MANY = 2;</code>
     */
    public static final int ONE2MANY_VALUE = 2;
    /**
     * <pre>
     * There can only be a single out-edge of this label for a given vertex but multiple in-edges (i.e. out-unique).
     * </pre>
     *
     * <code>MANY2ONE = 3;</code>
     */
    public static final int MANY2ONE_VALUE = 3;
    /**
     * <pre>
     * There can be only a single in and out-edge of this label for a given vertex (i.e. unique in both directions).
     * </pre>
     *
     * <code>ONE2ONE = 4;</code>
     */
    public static final int ONE2ONE_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Multiplicity valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Multiplicity forNumber(int value) {
      switch (value) {
        case 0: return MULTI;
        case 1: return SIMPLE;
        case 2: return ONE2MANY;
        case 3: return MANY2ONE;
        case 4: return ONE2ONE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Multiplicity>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Multiplicity> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Multiplicity>() {
            public Multiplicity findValueByNumber(int number) {
              return Multiplicity.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.janusgraph.graphdb.grpc.types.EdgeLabel.getDescriptor().getEnumTypes().get(1);
    }

    private static final Multiplicity[] VALUES = values();

    public static Multiplicity valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Multiplicity(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:janusgraph.types.v1.EdgeLabel.Multiplicity)
  }

  public static final int ID_FIELD_NUMBER = 1;
  private com.google.protobuf.Int64Value id_;
  /**
   * <pre>
   * The Internal id.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value id = 1 [json_name = "id"];</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return id_ != null;
  }
  /**
   * <pre>
   * The Internal id.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public com.google.protobuf.Int64Value getId() {
    return id_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : id_;
  }
  /**
   * <pre>
   * The Internal id.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value id = 1 [json_name = "id"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Int64ValueOrBuilder getIdOrBuilder() {
    return getId();
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * The EdgeLabel Name.
   * </pre>
   *
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The EdgeLabel Name.
   * </pre>
   *
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIRECTION_FIELD_NUMBER = 3;
  private int direction_;
  /**
   * <pre>
   * Defines queryable direction.
   * </pre>
   *
   * <code>.janusgraph.types.v1.EdgeLabel.Direction direction = 3 [json_name = "direction"];</code>
   * @return The enum numeric value on the wire for direction.
   */
  @java.lang.Override public int getDirectionValue() {
    return direction_;
  }
  /**
   * <pre>
   * Defines queryable direction.
   * </pre>
   *
   * <code>.janusgraph.types.v1.EdgeLabel.Direction direction = 3 [json_name = "direction"];</code>
   * @return The direction.
   */
  @java.lang.Override public org.janusgraph.graphdb.grpc.types.EdgeLabel.Direction getDirection() {
    @SuppressWarnings("deprecation")
    org.janusgraph.graphdb.grpc.types.EdgeLabel.Direction result = org.janusgraph.graphdb.grpc.types.EdgeLabel.Direction.valueOf(direction_);
    return result == null ? org.janusgraph.graphdb.grpc.types.EdgeLabel.Direction.UNRECOGNIZED : result;
  }

  public static final int MULTIPLICITY_FIELD_NUMBER = 4;
  private int multiplicity_;
  /**
   * <pre>
   * Defines Multiplicity of a edge.
   * </pre>
   *
   * <code>.janusgraph.types.v1.EdgeLabel.Multiplicity multiplicity = 4 [json_name = "multiplicity"];</code>
   * @return The enum numeric value on the wire for multiplicity.
   */
  @java.lang.Override public int getMultiplicityValue() {
    return multiplicity_;
  }
  /**
   * <pre>
   * Defines Multiplicity of a edge.
   * </pre>
   *
   * <code>.janusgraph.types.v1.EdgeLabel.Multiplicity multiplicity = 4 [json_name = "multiplicity"];</code>
   * @return The multiplicity.
   */
  @java.lang.Override public org.janusgraph.graphdb.grpc.types.EdgeLabel.Multiplicity getMultiplicity() {
    @SuppressWarnings("deprecation")
    org.janusgraph.graphdb.grpc.types.EdgeLabel.Multiplicity result = org.janusgraph.graphdb.grpc.types.EdgeLabel.Multiplicity.valueOf(multiplicity_);
    return result == null ? org.janusgraph.graphdb.grpc.types.EdgeLabel.Multiplicity.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != null) {
      output.writeMessage(1, getId());
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (direction_ != org.janusgraph.graphdb.grpc.types.EdgeLabel.Direction.BOTH.getNumber()) {
      output.writeEnum(3, direction_);
    }
    if (multiplicity_ != org.janusgraph.graphdb.grpc.types.EdgeLabel.Multiplicity.MULTI.getNumber()) {
      output.writeEnum(4, multiplicity_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getId());
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (direction_ != org.janusgraph.graphdb.grpc.types.EdgeLabel.Direction.BOTH.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, direction_);
    }
    if (multiplicity_ != org.janusgraph.graphdb.grpc.types.EdgeLabel.Multiplicity.MULTI.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, multiplicity_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.janusgraph.graphdb.grpc.types.EdgeLabel)) {
      return super.equals(obj);
    }
    org.janusgraph.graphdb.grpc.types.EdgeLabel other = (org.janusgraph.graphdb.grpc.types.EdgeLabel) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (!getName()
        .equals(other.getName())) return false;
    if (direction_ != other.direction_) return false;
    if (multiplicity_ != other.multiplicity_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + direction_;
    hash = (37 * hash) + MULTIPLICITY_FIELD_NUMBER;
    hash = (53 * hash) + multiplicity_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.janusgraph.graphdb.grpc.types.EdgeLabel parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.janusgraph.graphdb.grpc.types.EdgeLabel parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.types.EdgeLabel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.janusgraph.graphdb.grpc.types.EdgeLabel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.types.EdgeLabel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.janusgraph.graphdb.grpc.types.EdgeLabel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.types.EdgeLabel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.janusgraph.graphdb.grpc.types.EdgeLabel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.types.EdgeLabel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.janusgraph.graphdb.grpc.types.EdgeLabel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.types.EdgeLabel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.janusgraph.graphdb.grpc.types.EdgeLabel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.janusgraph.graphdb.grpc.types.EdgeLabel prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code janusgraph.types.v1.EdgeLabel}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:janusgraph.types.v1.EdgeLabel)
      org.janusgraph.graphdb.grpc.types.EdgeLabelOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.janusgraph.graphdb.grpc.types.SchemaTypes.internal_static_janusgraph_types_v1_EdgeLabel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.janusgraph.graphdb.grpc.types.SchemaTypes.internal_static_janusgraph_types_v1_EdgeLabel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.janusgraph.graphdb.grpc.types.EdgeLabel.class, org.janusgraph.graphdb.grpc.types.EdgeLabel.Builder.class);
    }

    // Construct using org.janusgraph.graphdb.grpc.types.EdgeLabel.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (idBuilder_ == null) {
        id_ = null;
      } else {
        id_ = null;
        idBuilder_ = null;
      }
      name_ = "";

      direction_ = 0;

      multiplicity_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.janusgraph.graphdb.grpc.types.SchemaTypes.internal_static_janusgraph_types_v1_EdgeLabel_descriptor;
    }

    @java.lang.Override
    public org.janusgraph.graphdb.grpc.types.EdgeLabel getDefaultInstanceForType() {
      return org.janusgraph.graphdb.grpc.types.EdgeLabel.getDefaultInstance();
    }

    @java.lang.Override
    public org.janusgraph.graphdb.grpc.types.EdgeLabel build() {
      org.janusgraph.graphdb.grpc.types.EdgeLabel result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.janusgraph.graphdb.grpc.types.EdgeLabel buildPartial() {
      org.janusgraph.graphdb.grpc.types.EdgeLabel result = new org.janusgraph.graphdb.grpc.types.EdgeLabel(this);
      if (idBuilder_ == null) {
        result.id_ = id_;
      } else {
        result.id_ = idBuilder_.build();
      }
      result.name_ = name_;
      result.direction_ = direction_;
      result.multiplicity_ = multiplicity_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.janusgraph.graphdb.grpc.types.EdgeLabel) {
        return mergeFrom((org.janusgraph.graphdb.grpc.types.EdgeLabel)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.janusgraph.graphdb.grpc.types.EdgeLabel other) {
      if (other == org.janusgraph.graphdb.grpc.types.EdgeLabel.getDefaultInstance()) return this;
      if (other.hasId()) {
        mergeId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.direction_ != 0) {
        setDirectionValue(other.getDirectionValue());
      }
      if (other.multiplicity_ != 0) {
        setMultiplicityValue(other.getMultiplicityValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.janusgraph.graphdb.grpc.types.EdgeLabel parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.janusgraph.graphdb.grpc.types.EdgeLabel) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.Int64Value id_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> idBuilder_;
    /**
     * <pre>
     * The Internal id.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value id = 1 [json_name = "id"];</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return idBuilder_ != null || id_ != null;
    }
    /**
     * <pre>
     * The Internal id.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    public com.google.protobuf.Int64Value getId() {
      if (idBuilder_ == null) {
        return id_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The Internal id.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value id = 1 [json_name = "id"];</code>
     */
    public Builder setId(com.google.protobuf.Int64Value value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
        onChanged();
      } else {
        idBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The Internal id.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value id = 1 [json_name = "id"];</code>
     */
    public Builder setId(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
        onChanged();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The Internal id.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value id = 1 [json_name = "id"];</code>
     */
    public Builder mergeId(com.google.protobuf.Int64Value value) {
      if (idBuilder_ == null) {
        if (id_ != null) {
          id_ =
            com.google.protobuf.Int64Value.newBuilder(id_).mergeFrom(value).buildPartial();
        } else {
          id_ = value;
        }
        onChanged();
      } else {
        idBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The Internal id.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value id = 1 [json_name = "id"];</code>
     */
    public Builder clearId() {
      if (idBuilder_ == null) {
        id_ = null;
        onChanged();
      } else {
        id_ = null;
        idBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The Internal id.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value id = 1 [json_name = "id"];</code>
     */
    public com.google.protobuf.Int64Value.Builder getIdBuilder() {
      
      onChanged();
      return getIdFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The Internal id.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value id = 1 [json_name = "id"];</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : id_;
      }
    }
    /**
     * <pre>
     * The Internal id.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value id = 1 [json_name = "id"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * The EdgeLabel Name.
     * </pre>
     *
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The EdgeLabel Name.
     * </pre>
     *
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The EdgeLabel Name.
     * </pre>
     *
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The EdgeLabel Name.
     * </pre>
     *
     * <code>string name = 2 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The EdgeLabel Name.
     * </pre>
     *
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int direction_ = 0;
    /**
     * <pre>
     * Defines queryable direction.
     * </pre>
     *
     * <code>.janusgraph.types.v1.EdgeLabel.Direction direction = 3 [json_name = "direction"];</code>
     * @return The enum numeric value on the wire for direction.
     */
    @java.lang.Override public int getDirectionValue() {
      return direction_;
    }
    /**
     * <pre>
     * Defines queryable direction.
     * </pre>
     *
     * <code>.janusgraph.types.v1.EdgeLabel.Direction direction = 3 [json_name = "direction"];</code>
     * @param value The enum numeric value on the wire for direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirectionValue(int value) {
      
      direction_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Defines queryable direction.
     * </pre>
     *
     * <code>.janusgraph.types.v1.EdgeLabel.Direction direction = 3 [json_name = "direction"];</code>
     * @return The direction.
     */
    @java.lang.Override
    public org.janusgraph.graphdb.grpc.types.EdgeLabel.Direction getDirection() {
      @SuppressWarnings("deprecation")
      org.janusgraph.graphdb.grpc.types.EdgeLabel.Direction result = org.janusgraph.graphdb.grpc.types.EdgeLabel.Direction.valueOf(direction_);
      return result == null ? org.janusgraph.graphdb.grpc.types.EdgeLabel.Direction.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Defines queryable direction.
     * </pre>
     *
     * <code>.janusgraph.types.v1.EdgeLabel.Direction direction = 3 [json_name = "direction"];</code>
     * @param value The direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirection(org.janusgraph.graphdb.grpc.types.EdgeLabel.Direction value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      direction_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Defines queryable direction.
     * </pre>
     *
     * <code>.janusgraph.types.v1.EdgeLabel.Direction direction = 3 [json_name = "direction"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDirection() {
      
      direction_ = 0;
      onChanged();
      return this;
    }

    private int multiplicity_ = 0;
    /**
     * <pre>
     * Defines Multiplicity of a edge.
     * </pre>
     *
     * <code>.janusgraph.types.v1.EdgeLabel.Multiplicity multiplicity = 4 [json_name = "multiplicity"];</code>
     * @return The enum numeric value on the wire for multiplicity.
     */
    @java.lang.Override public int getMultiplicityValue() {
      return multiplicity_;
    }
    /**
     * <pre>
     * Defines Multiplicity of a edge.
     * </pre>
     *
     * <code>.janusgraph.types.v1.EdgeLabel.Multiplicity multiplicity = 4 [json_name = "multiplicity"];</code>
     * @param value The enum numeric value on the wire for multiplicity to set.
     * @return This builder for chaining.
     */
    public Builder setMultiplicityValue(int value) {
      
      multiplicity_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Defines Multiplicity of a edge.
     * </pre>
     *
     * <code>.janusgraph.types.v1.EdgeLabel.Multiplicity multiplicity = 4 [json_name = "multiplicity"];</code>
     * @return The multiplicity.
     */
    @java.lang.Override
    public org.janusgraph.graphdb.grpc.types.EdgeLabel.Multiplicity getMultiplicity() {
      @SuppressWarnings("deprecation")
      org.janusgraph.graphdb.grpc.types.EdgeLabel.Multiplicity result = org.janusgraph.graphdb.grpc.types.EdgeLabel.Multiplicity.valueOf(multiplicity_);
      return result == null ? org.janusgraph.graphdb.grpc.types.EdgeLabel.Multiplicity.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Defines Multiplicity of a edge.
     * </pre>
     *
     * <code>.janusgraph.types.v1.EdgeLabel.Multiplicity multiplicity = 4 [json_name = "multiplicity"];</code>
     * @param value The multiplicity to set.
     * @return This builder for chaining.
     */
    public Builder setMultiplicity(org.janusgraph.graphdb.grpc.types.EdgeLabel.Multiplicity value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      multiplicity_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Defines Multiplicity of a edge.
     * </pre>
     *
     * <code>.janusgraph.types.v1.EdgeLabel.Multiplicity multiplicity = 4 [json_name = "multiplicity"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMultiplicity() {
      
      multiplicity_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:janusgraph.types.v1.EdgeLabel)
  }

  // @@protoc_insertion_point(class_scope:janusgraph.types.v1.EdgeLabel)
  private static final org.janusgraph.graphdb.grpc.types.EdgeLabel DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.janusgraph.graphdb.grpc.types.EdgeLabel();
  }

  public static org.janusgraph.graphdb.grpc.types.EdgeLabel getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EdgeLabel>
      PARSER = new com.google.protobuf.AbstractParser<EdgeLabel>() {
    @java.lang.Override
    public EdgeLabel parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EdgeLabel(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EdgeLabel> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EdgeLabel> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.janusgraph.graphdb.grpc.types.EdgeLabel getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

