// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: janusgraph/types/v1/graph_types.proto

package org.janusgraph.graphdb.grpc.types;

public final class GraphTypes {
  private GraphTypes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_janusgraph_types_v1_JanusGraphContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_janusgraph_types_v1_JanusGraphContext_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%janusgraph/types/v1/graph_types.proto\022" +
      "\023janusgraph.types.v1\"2\n\021JanusGraphContex" +
      "t\022\035\n\ngraph_name\030\001 \001(\tR\tgraphNameB%\n!org." +
      "janusgraph.graphdb.grpc.typesP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_janusgraph_types_v1_JanusGraphContext_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_janusgraph_types_v1_JanusGraphContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_janusgraph_types_v1_JanusGraphContext_descriptor,
        new java.lang.String[] { "GraphName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
