// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: janusgraph/types/v1/graph_types.proto

package org.janusgraph.graphdb.grpc.types;

public interface JanusGraphContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:janusgraph.types.v1.JanusGraphContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string graph_name = 1 [json_name = "graphName"];</code>
   * @return The graphName.
   */
  java.lang.String getGraphName();
  /**
   * <code>string graph_name = 1 [json_name = "graphName"];</code>
   * @return The bytes for graphName.
   */
  com.google.protobuf.ByteString
      getGraphNameBytes();
}
