// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: janusgraph/types/v1/schema_types.proto

package org.janusgraph.graphdb.grpc.types;

public final class SchemaTypes {
  private SchemaTypes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_janusgraph_types_v1_VertexLabel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_janusgraph_types_v1_VertexLabel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_janusgraph_types_v1_EdgeLabel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_janusgraph_types_v1_EdgeLabel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&janusgraph/types/v1/schema_types.proto" +
      "\022\023janusgraph.types.v1\032\036google/protobuf/w" +
      "rappers.proto\"\215\001\n\013VertexLabel\022+\n\002id\030\001 \001(" +
      "\0132\033.google.protobuf.Int64ValueR\002id\022\022\n\004na" +
      "me\030\002 \001(\tR\004name\022\033\n\tread_only\030\003 \001(\010R\010readO" +
      "nly\022 \n\013partitioned\030\004 \001(\010R\013partitioned\"\325\002" +
      "\n\tEdgeLabel\022+\n\002id\030\001 \001(\0132\033.google.protobu" +
      "f.Int64ValueR\002id\022\022\n\004name\030\002 \001(\tR\004name\022F\n\t" +
      "direction\030\003 \001(\0162(.janusgraph.types.v1.Ed" +
      "geLabel.DirectionR\tdirection\022O\n\014multipli" +
      "city\030\004 \001(\0162+.janusgraph.types.v1.EdgeLab" +
      "el.MultiplicityR\014multiplicity\"\036\n\tDirecti" +
      "on\022\010\n\004BOTH\020\000\022\007\n\003OUT\020\001\"N\n\014Multiplicity\022\t\n" +
      "\005MULTI\020\000\022\n\n\006SIMPLE\020\001\022\014\n\010ONE2MANY\020\002\022\014\n\010MA" +
      "NY2ONE\020\003\022\013\n\007ONE2ONE\020\004B%\n!org.janusgraph." +
      "graphdb.grpc.typesP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_janusgraph_types_v1_VertexLabel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_janusgraph_types_v1_VertexLabel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_janusgraph_types_v1_VertexLabel_descriptor,
        new java.lang.String[] { "Id", "Name", "ReadOnly", "Partitioned", });
    internal_static_janusgraph_types_v1_EdgeLabel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_janusgraph_types_v1_EdgeLabel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_janusgraph_types_v1_EdgeLabel_descriptor,
        new java.lang.String[] { "Id", "Name", "Direction", "Multiplicity", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
