// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: janusgraph/types/v1/schema_types.proto

package org.janusgraph.graphdb.grpc.types;

public interface VertexLabelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:janusgraph.types.v1.VertexLabel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The Internal id.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value id = 1 [json_name = "id"];</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <pre>
   * The Internal id.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  com.google.protobuf.Int64Value getId();
  /**
   * <pre>
   * The Internal id.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value id = 1 [json_name = "id"];</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getIdOrBuilder();

  /**
   * <pre>
   * The VertexLabel Name.
   * </pre>
   *
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The VertexLabel Name.
   * </pre>
   *
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Marking as readOnly, default not readOnly.
   * </pre>
   *
   * <code>bool read_only = 3 [json_name = "readOnly"];</code>
   * @return The readOnly.
   */
  boolean getReadOnly();

  /**
   * <pre>
   * Marking as partitioned, default not partitioned.
   * </pre>
   *
   * <code>bool partitioned = 4 [json_name = "partitioned"];</code>
   * @return The partitioned.
   */
  boolean getPartitioned();
}
