// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: janusgraph/schema/v1/schema_manager.proto

package org.janusgraph.graphdb.grpc.schema;

public interface GetEdgeLabelsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:janusgraph.schema.v1.GetEdgeLabelsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .janusgraph.types.v1.EdgeLabel edge_labels = 1 [json_name = "edgeLabels"];</code>
   */
  java.util.List<org.janusgraph.graphdb.grpc.types.EdgeLabel> 
      getEdgeLabelsList();
  /**
   * <code>repeated .janusgraph.types.v1.EdgeLabel edge_labels = 1 [json_name = "edgeLabels"];</code>
   */
  org.janusgraph.graphdb.grpc.types.EdgeLabel getEdgeLabels(int index);
  /**
   * <code>repeated .janusgraph.types.v1.EdgeLabel edge_labels = 1 [json_name = "edgeLabels"];</code>
   */
  int getEdgeLabelsCount();
  /**
   * <code>repeated .janusgraph.types.v1.EdgeLabel edge_labels = 1 [json_name = "edgeLabels"];</code>
   */
  java.util.List<? extends org.janusgraph.graphdb.grpc.types.EdgeLabelOrBuilder> 
      getEdgeLabelsOrBuilderList();
  /**
   * <code>repeated .janusgraph.types.v1.EdgeLabel edge_labels = 1 [json_name = "edgeLabels"];</code>
   */
  org.janusgraph.graphdb.grpc.types.EdgeLabelOrBuilder getEdgeLabelsOrBuilder(
      int index);
}
