// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: janusgraph/schema/v1/schema_manager.proto

package org.janusgraph.graphdb.grpc.schema;

/**
 * Protobuf type {@code janusgraph.schema.v1.GetEdgeLabelByNameResponse}
 */
public final class GetEdgeLabelByNameResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:janusgraph.schema.v1.GetEdgeLabelByNameResponse)
    GetEdgeLabelByNameResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetEdgeLabelByNameResponse.newBuilder() to construct.
  private GetEdgeLabelByNameResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetEdgeLabelByNameResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetEdgeLabelByNameResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetEdgeLabelByNameResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.janusgraph.graphdb.grpc.types.EdgeLabel.Builder subBuilder = null;
            if (edgeLabel_ != null) {
              subBuilder = edgeLabel_.toBuilder();
            }
            edgeLabel_ = input.readMessage(org.janusgraph.graphdb.grpc.types.EdgeLabel.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(edgeLabel_);
              edgeLabel_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.janusgraph.graphdb.grpc.schema.SchemaManager.internal_static_janusgraph_schema_v1_GetEdgeLabelByNameResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.janusgraph.graphdb.grpc.schema.SchemaManager.internal_static_janusgraph_schema_v1_GetEdgeLabelByNameResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse.class, org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse.Builder.class);
  }

  public static final int EDGE_LABEL_FIELD_NUMBER = 1;
  private org.janusgraph.graphdb.grpc.types.EdgeLabel edgeLabel_;
  /**
   * <code>.janusgraph.types.v1.EdgeLabel edge_label = 1 [json_name = "edgeLabel"];</code>
   * @return Whether the edgeLabel field is set.
   */
  @java.lang.Override
  public boolean hasEdgeLabel() {
    return edgeLabel_ != null;
  }
  /**
   * <code>.janusgraph.types.v1.EdgeLabel edge_label = 1 [json_name = "edgeLabel"];</code>
   * @return The edgeLabel.
   */
  @java.lang.Override
  public org.janusgraph.graphdb.grpc.types.EdgeLabel getEdgeLabel() {
    return edgeLabel_ == null ? org.janusgraph.graphdb.grpc.types.EdgeLabel.getDefaultInstance() : edgeLabel_;
  }
  /**
   * <code>.janusgraph.types.v1.EdgeLabel edge_label = 1 [json_name = "edgeLabel"];</code>
   */
  @java.lang.Override
  public org.janusgraph.graphdb.grpc.types.EdgeLabelOrBuilder getEdgeLabelOrBuilder() {
    return getEdgeLabel();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (edgeLabel_ != null) {
      output.writeMessage(1, getEdgeLabel());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (edgeLabel_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getEdgeLabel());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse)) {
      return super.equals(obj);
    }
    org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse other = (org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse) obj;

    if (hasEdgeLabel() != other.hasEdgeLabel()) return false;
    if (hasEdgeLabel()) {
      if (!getEdgeLabel()
          .equals(other.getEdgeLabel())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEdgeLabel()) {
      hash = (37 * hash) + EDGE_LABEL_FIELD_NUMBER;
      hash = (53 * hash) + getEdgeLabel().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code janusgraph.schema.v1.GetEdgeLabelByNameResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:janusgraph.schema.v1.GetEdgeLabelByNameResponse)
      org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.janusgraph.graphdb.grpc.schema.SchemaManager.internal_static_janusgraph_schema_v1_GetEdgeLabelByNameResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.janusgraph.graphdb.grpc.schema.SchemaManager.internal_static_janusgraph_schema_v1_GetEdgeLabelByNameResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse.class, org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse.Builder.class);
    }

    // Construct using org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (edgeLabelBuilder_ == null) {
        edgeLabel_ = null;
      } else {
        edgeLabel_ = null;
        edgeLabelBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.janusgraph.graphdb.grpc.schema.SchemaManager.internal_static_janusgraph_schema_v1_GetEdgeLabelByNameResponse_descriptor;
    }

    @java.lang.Override
    public org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse getDefaultInstanceForType() {
      return org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse build() {
      org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse buildPartial() {
      org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse result = new org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse(this);
      if (edgeLabelBuilder_ == null) {
        result.edgeLabel_ = edgeLabel_;
      } else {
        result.edgeLabel_ = edgeLabelBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse) {
        return mergeFrom((org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse other) {
      if (other == org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse.getDefaultInstance()) return this;
      if (other.hasEdgeLabel()) {
        mergeEdgeLabel(other.getEdgeLabel());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.janusgraph.graphdb.grpc.types.EdgeLabel edgeLabel_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.janusgraph.graphdb.grpc.types.EdgeLabel, org.janusgraph.graphdb.grpc.types.EdgeLabel.Builder, org.janusgraph.graphdb.grpc.types.EdgeLabelOrBuilder> edgeLabelBuilder_;
    /**
     * <code>.janusgraph.types.v1.EdgeLabel edge_label = 1 [json_name = "edgeLabel"];</code>
     * @return Whether the edgeLabel field is set.
     */
    public boolean hasEdgeLabel() {
      return edgeLabelBuilder_ != null || edgeLabel_ != null;
    }
    /**
     * <code>.janusgraph.types.v1.EdgeLabel edge_label = 1 [json_name = "edgeLabel"];</code>
     * @return The edgeLabel.
     */
    public org.janusgraph.graphdb.grpc.types.EdgeLabel getEdgeLabel() {
      if (edgeLabelBuilder_ == null) {
        return edgeLabel_ == null ? org.janusgraph.graphdb.grpc.types.EdgeLabel.getDefaultInstance() : edgeLabel_;
      } else {
        return edgeLabelBuilder_.getMessage();
      }
    }
    /**
     * <code>.janusgraph.types.v1.EdgeLabel edge_label = 1 [json_name = "edgeLabel"];</code>
     */
    public Builder setEdgeLabel(org.janusgraph.graphdb.grpc.types.EdgeLabel value) {
      if (edgeLabelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        edgeLabel_ = value;
        onChanged();
      } else {
        edgeLabelBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.janusgraph.types.v1.EdgeLabel edge_label = 1 [json_name = "edgeLabel"];</code>
     */
    public Builder setEdgeLabel(
        org.janusgraph.graphdb.grpc.types.EdgeLabel.Builder builderForValue) {
      if (edgeLabelBuilder_ == null) {
        edgeLabel_ = builderForValue.build();
        onChanged();
      } else {
        edgeLabelBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.janusgraph.types.v1.EdgeLabel edge_label = 1 [json_name = "edgeLabel"];</code>
     */
    public Builder mergeEdgeLabel(org.janusgraph.graphdb.grpc.types.EdgeLabel value) {
      if (edgeLabelBuilder_ == null) {
        if (edgeLabel_ != null) {
          edgeLabel_ =
            org.janusgraph.graphdb.grpc.types.EdgeLabel.newBuilder(edgeLabel_).mergeFrom(value).buildPartial();
        } else {
          edgeLabel_ = value;
        }
        onChanged();
      } else {
        edgeLabelBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.janusgraph.types.v1.EdgeLabel edge_label = 1 [json_name = "edgeLabel"];</code>
     */
    public Builder clearEdgeLabel() {
      if (edgeLabelBuilder_ == null) {
        edgeLabel_ = null;
        onChanged();
      } else {
        edgeLabel_ = null;
        edgeLabelBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.janusgraph.types.v1.EdgeLabel edge_label = 1 [json_name = "edgeLabel"];</code>
     */
    public org.janusgraph.graphdb.grpc.types.EdgeLabel.Builder getEdgeLabelBuilder() {
      
      onChanged();
      return getEdgeLabelFieldBuilder().getBuilder();
    }
    /**
     * <code>.janusgraph.types.v1.EdgeLabel edge_label = 1 [json_name = "edgeLabel"];</code>
     */
    public org.janusgraph.graphdb.grpc.types.EdgeLabelOrBuilder getEdgeLabelOrBuilder() {
      if (edgeLabelBuilder_ != null) {
        return edgeLabelBuilder_.getMessageOrBuilder();
      } else {
        return edgeLabel_ == null ?
            org.janusgraph.graphdb.grpc.types.EdgeLabel.getDefaultInstance() : edgeLabel_;
      }
    }
    /**
     * <code>.janusgraph.types.v1.EdgeLabel edge_label = 1 [json_name = "edgeLabel"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.janusgraph.graphdb.grpc.types.EdgeLabel, org.janusgraph.graphdb.grpc.types.EdgeLabel.Builder, org.janusgraph.graphdb.grpc.types.EdgeLabelOrBuilder> 
        getEdgeLabelFieldBuilder() {
      if (edgeLabelBuilder_ == null) {
        edgeLabelBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.janusgraph.graphdb.grpc.types.EdgeLabel, org.janusgraph.graphdb.grpc.types.EdgeLabel.Builder, org.janusgraph.graphdb.grpc.types.EdgeLabelOrBuilder>(
                getEdgeLabel(),
                getParentForChildren(),
                isClean());
        edgeLabel_ = null;
      }
      return edgeLabelBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:janusgraph.schema.v1.GetEdgeLabelByNameResponse)
  }

  // @@protoc_insertion_point(class_scope:janusgraph.schema.v1.GetEdgeLabelByNameResponse)
  private static final org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse();
  }

  public static org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetEdgeLabelByNameResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetEdgeLabelByNameResponse>() {
    @java.lang.Override
    public GetEdgeLabelByNameResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetEdgeLabelByNameResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetEdgeLabelByNameResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetEdgeLabelByNameResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.janusgraph.graphdb.grpc.schema.GetEdgeLabelByNameResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

