// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: janusgraph/schema/v1/schema_manager.proto

package org.janusgraph.graphdb.grpc.schema;

public interface GetVertexLabelsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:janusgraph.schema.v1.GetVertexLabelsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
   */
  java.util.List<org.janusgraph.graphdb.grpc.types.VertexLabel> 
      getVertexLabelsList();
  /**
   * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
   */
  org.janusgraph.graphdb.grpc.types.VertexLabel getVertexLabels(int index);
  /**
   * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
   */
  int getVertexLabelsCount();
  /**
   * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
   */
  java.util.List<? extends org.janusgraph.graphdb.grpc.types.VertexLabelOrBuilder> 
      getVertexLabelsOrBuilderList();
  /**
   * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
   */
  org.janusgraph.graphdb.grpc.types.VertexLabelOrBuilder getVertexLabelsOrBuilder(
      int index);
}
