// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: janusgraph/schema/v1/schema_manager.proto

package org.janusgraph.graphdb.grpc.schema;

/**
 * Protobuf type {@code janusgraph.schema.v1.GetVertexLabelByNameResponse}
 */
public final class GetVertexLabelByNameResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:janusgraph.schema.v1.GetVertexLabelByNameResponse)
    GetVertexLabelByNameResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetVertexLabelByNameResponse.newBuilder() to construct.
  private GetVertexLabelByNameResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetVertexLabelByNameResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetVertexLabelByNameResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetVertexLabelByNameResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.janusgraph.graphdb.grpc.types.VertexLabel.Builder subBuilder = null;
            if (vertexLabel_ != null) {
              subBuilder = vertexLabel_.toBuilder();
            }
            vertexLabel_ = input.readMessage(org.janusgraph.graphdb.grpc.types.VertexLabel.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(vertexLabel_);
              vertexLabel_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.janusgraph.graphdb.grpc.schema.SchemaManager.internal_static_janusgraph_schema_v1_GetVertexLabelByNameResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.janusgraph.graphdb.grpc.schema.SchemaManager.internal_static_janusgraph_schema_v1_GetVertexLabelByNameResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse.class, org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse.Builder.class);
  }

  public static final int VERTEX_LABEL_FIELD_NUMBER = 1;
  private org.janusgraph.graphdb.grpc.types.VertexLabel vertexLabel_;
  /**
   * <code>.janusgraph.types.v1.VertexLabel vertex_label = 1 [json_name = "vertexLabel"];</code>
   * @return Whether the vertexLabel field is set.
   */
  @java.lang.Override
  public boolean hasVertexLabel() {
    return vertexLabel_ != null;
  }
  /**
   * <code>.janusgraph.types.v1.VertexLabel vertex_label = 1 [json_name = "vertexLabel"];</code>
   * @return The vertexLabel.
   */
  @java.lang.Override
  public org.janusgraph.graphdb.grpc.types.VertexLabel getVertexLabel() {
    return vertexLabel_ == null ? org.janusgraph.graphdb.grpc.types.VertexLabel.getDefaultInstance() : vertexLabel_;
  }
  /**
   * <code>.janusgraph.types.v1.VertexLabel vertex_label = 1 [json_name = "vertexLabel"];</code>
   */
  @java.lang.Override
  public org.janusgraph.graphdb.grpc.types.VertexLabelOrBuilder getVertexLabelOrBuilder() {
    return getVertexLabel();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (vertexLabel_ != null) {
      output.writeMessage(1, getVertexLabel());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (vertexLabel_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getVertexLabel());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse)) {
      return super.equals(obj);
    }
    org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse other = (org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse) obj;

    if (hasVertexLabel() != other.hasVertexLabel()) return false;
    if (hasVertexLabel()) {
      if (!getVertexLabel()
          .equals(other.getVertexLabel())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasVertexLabel()) {
      hash = (37 * hash) + VERTEX_LABEL_FIELD_NUMBER;
      hash = (53 * hash) + getVertexLabel().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code janusgraph.schema.v1.GetVertexLabelByNameResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:janusgraph.schema.v1.GetVertexLabelByNameResponse)
      org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.janusgraph.graphdb.grpc.schema.SchemaManager.internal_static_janusgraph_schema_v1_GetVertexLabelByNameResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.janusgraph.graphdb.grpc.schema.SchemaManager.internal_static_janusgraph_schema_v1_GetVertexLabelByNameResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse.class, org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse.Builder.class);
    }

    // Construct using org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (vertexLabelBuilder_ == null) {
        vertexLabel_ = null;
      } else {
        vertexLabel_ = null;
        vertexLabelBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.janusgraph.graphdb.grpc.schema.SchemaManager.internal_static_janusgraph_schema_v1_GetVertexLabelByNameResponse_descriptor;
    }

    @java.lang.Override
    public org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse getDefaultInstanceForType() {
      return org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse build() {
      org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse buildPartial() {
      org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse result = new org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse(this);
      if (vertexLabelBuilder_ == null) {
        result.vertexLabel_ = vertexLabel_;
      } else {
        result.vertexLabel_ = vertexLabelBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse) {
        return mergeFrom((org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse other) {
      if (other == org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse.getDefaultInstance()) return this;
      if (other.hasVertexLabel()) {
        mergeVertexLabel(other.getVertexLabel());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.janusgraph.graphdb.grpc.types.VertexLabel vertexLabel_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.janusgraph.graphdb.grpc.types.VertexLabel, org.janusgraph.graphdb.grpc.types.VertexLabel.Builder, org.janusgraph.graphdb.grpc.types.VertexLabelOrBuilder> vertexLabelBuilder_;
    /**
     * <code>.janusgraph.types.v1.VertexLabel vertex_label = 1 [json_name = "vertexLabel"];</code>
     * @return Whether the vertexLabel field is set.
     */
    public boolean hasVertexLabel() {
      return vertexLabelBuilder_ != null || vertexLabel_ != null;
    }
    /**
     * <code>.janusgraph.types.v1.VertexLabel vertex_label = 1 [json_name = "vertexLabel"];</code>
     * @return The vertexLabel.
     */
    public org.janusgraph.graphdb.grpc.types.VertexLabel getVertexLabel() {
      if (vertexLabelBuilder_ == null) {
        return vertexLabel_ == null ? org.janusgraph.graphdb.grpc.types.VertexLabel.getDefaultInstance() : vertexLabel_;
      } else {
        return vertexLabelBuilder_.getMessage();
      }
    }
    /**
     * <code>.janusgraph.types.v1.VertexLabel vertex_label = 1 [json_name = "vertexLabel"];</code>
     */
    public Builder setVertexLabel(org.janusgraph.graphdb.grpc.types.VertexLabel value) {
      if (vertexLabelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        vertexLabel_ = value;
        onChanged();
      } else {
        vertexLabelBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.janusgraph.types.v1.VertexLabel vertex_label = 1 [json_name = "vertexLabel"];</code>
     */
    public Builder setVertexLabel(
        org.janusgraph.graphdb.grpc.types.VertexLabel.Builder builderForValue) {
      if (vertexLabelBuilder_ == null) {
        vertexLabel_ = builderForValue.build();
        onChanged();
      } else {
        vertexLabelBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.janusgraph.types.v1.VertexLabel vertex_label = 1 [json_name = "vertexLabel"];</code>
     */
    public Builder mergeVertexLabel(org.janusgraph.graphdb.grpc.types.VertexLabel value) {
      if (vertexLabelBuilder_ == null) {
        if (vertexLabel_ != null) {
          vertexLabel_ =
            org.janusgraph.graphdb.grpc.types.VertexLabel.newBuilder(vertexLabel_).mergeFrom(value).buildPartial();
        } else {
          vertexLabel_ = value;
        }
        onChanged();
      } else {
        vertexLabelBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.janusgraph.types.v1.VertexLabel vertex_label = 1 [json_name = "vertexLabel"];</code>
     */
    public Builder clearVertexLabel() {
      if (vertexLabelBuilder_ == null) {
        vertexLabel_ = null;
        onChanged();
      } else {
        vertexLabel_ = null;
        vertexLabelBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.janusgraph.types.v1.VertexLabel vertex_label = 1 [json_name = "vertexLabel"];</code>
     */
    public org.janusgraph.graphdb.grpc.types.VertexLabel.Builder getVertexLabelBuilder() {
      
      onChanged();
      return getVertexLabelFieldBuilder().getBuilder();
    }
    /**
     * <code>.janusgraph.types.v1.VertexLabel vertex_label = 1 [json_name = "vertexLabel"];</code>
     */
    public org.janusgraph.graphdb.grpc.types.VertexLabelOrBuilder getVertexLabelOrBuilder() {
      if (vertexLabelBuilder_ != null) {
        return vertexLabelBuilder_.getMessageOrBuilder();
      } else {
        return vertexLabel_ == null ?
            org.janusgraph.graphdb.grpc.types.VertexLabel.getDefaultInstance() : vertexLabel_;
      }
    }
    /**
     * <code>.janusgraph.types.v1.VertexLabel vertex_label = 1 [json_name = "vertexLabel"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.janusgraph.graphdb.grpc.types.VertexLabel, org.janusgraph.graphdb.grpc.types.VertexLabel.Builder, org.janusgraph.graphdb.grpc.types.VertexLabelOrBuilder> 
        getVertexLabelFieldBuilder() {
      if (vertexLabelBuilder_ == null) {
        vertexLabelBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.janusgraph.graphdb.grpc.types.VertexLabel, org.janusgraph.graphdb.grpc.types.VertexLabel.Builder, org.janusgraph.graphdb.grpc.types.VertexLabelOrBuilder>(
                getVertexLabel(),
                getParentForChildren(),
                isClean());
        vertexLabel_ = null;
      }
      return vertexLabelBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:janusgraph.schema.v1.GetVertexLabelByNameResponse)
  }

  // @@protoc_insertion_point(class_scope:janusgraph.schema.v1.GetVertexLabelByNameResponse)
  private static final org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse();
  }

  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetVertexLabelByNameResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetVertexLabelByNameResponse>() {
    @java.lang.Override
    public GetVertexLabelByNameResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetVertexLabelByNameResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetVertexLabelByNameResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetVertexLabelByNameResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.janusgraph.graphdb.grpc.schema.GetVertexLabelByNameResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

