// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: janusgraph/schema/v1/schema_manager.proto

package org.janusgraph.graphdb.grpc.schema;

/**
 * Protobuf type {@code janusgraph.schema.v1.GetVertexLabelsResponse}
 */
public final class GetVertexLabelsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:janusgraph.schema.v1.GetVertexLabelsResponse)
    GetVertexLabelsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetVertexLabelsResponse.newBuilder() to construct.
  private GetVertexLabelsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetVertexLabelsResponse() {
    vertexLabels_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetVertexLabelsResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetVertexLabelsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              vertexLabels_ = new java.util.ArrayList<org.janusgraph.graphdb.grpc.types.VertexLabel>();
              mutable_bitField0_ |= 0x00000001;
            }
            vertexLabels_.add(
                input.readMessage(org.janusgraph.graphdb.grpc.types.VertexLabel.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        vertexLabels_ = java.util.Collections.unmodifiableList(vertexLabels_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.janusgraph.graphdb.grpc.schema.SchemaManager.internal_static_janusgraph_schema_v1_GetVertexLabelsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.janusgraph.graphdb.grpc.schema.SchemaManager.internal_static_janusgraph_schema_v1_GetVertexLabelsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse.class, org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse.Builder.class);
  }

  public static final int VERTEX_LABELS_FIELD_NUMBER = 1;
  private java.util.List<org.janusgraph.graphdb.grpc.types.VertexLabel> vertexLabels_;
  /**
   * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
   */
  @java.lang.Override
  public java.util.List<org.janusgraph.graphdb.grpc.types.VertexLabel> getVertexLabelsList() {
    return vertexLabels_;
  }
  /**
   * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.janusgraph.graphdb.grpc.types.VertexLabelOrBuilder> 
      getVertexLabelsOrBuilderList() {
    return vertexLabels_;
  }
  /**
   * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
   */
  @java.lang.Override
  public int getVertexLabelsCount() {
    return vertexLabels_.size();
  }
  /**
   * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
   */
  @java.lang.Override
  public org.janusgraph.graphdb.grpc.types.VertexLabel getVertexLabels(int index) {
    return vertexLabels_.get(index);
  }
  /**
   * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
   */
  @java.lang.Override
  public org.janusgraph.graphdb.grpc.types.VertexLabelOrBuilder getVertexLabelsOrBuilder(
      int index) {
    return vertexLabels_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < vertexLabels_.size(); i++) {
      output.writeMessage(1, vertexLabels_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < vertexLabels_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, vertexLabels_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse)) {
      return super.equals(obj);
    }
    org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse other = (org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse) obj;

    if (!getVertexLabelsList()
        .equals(other.getVertexLabelsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getVertexLabelsCount() > 0) {
      hash = (37 * hash) + VERTEX_LABELS_FIELD_NUMBER;
      hash = (53 * hash) + getVertexLabelsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code janusgraph.schema.v1.GetVertexLabelsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:janusgraph.schema.v1.GetVertexLabelsResponse)
      org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.janusgraph.graphdb.grpc.schema.SchemaManager.internal_static_janusgraph_schema_v1_GetVertexLabelsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.janusgraph.graphdb.grpc.schema.SchemaManager.internal_static_janusgraph_schema_v1_GetVertexLabelsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse.class, org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse.Builder.class);
    }

    // Construct using org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getVertexLabelsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (vertexLabelsBuilder_ == null) {
        vertexLabels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        vertexLabelsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.janusgraph.graphdb.grpc.schema.SchemaManager.internal_static_janusgraph_schema_v1_GetVertexLabelsResponse_descriptor;
    }

    @java.lang.Override
    public org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse getDefaultInstanceForType() {
      return org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse build() {
      org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse buildPartial() {
      org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse result = new org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse(this);
      int from_bitField0_ = bitField0_;
      if (vertexLabelsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          vertexLabels_ = java.util.Collections.unmodifiableList(vertexLabels_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.vertexLabels_ = vertexLabels_;
      } else {
        result.vertexLabels_ = vertexLabelsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse) {
        return mergeFrom((org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse other) {
      if (other == org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse.getDefaultInstance()) return this;
      if (vertexLabelsBuilder_ == null) {
        if (!other.vertexLabels_.isEmpty()) {
          if (vertexLabels_.isEmpty()) {
            vertexLabels_ = other.vertexLabels_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureVertexLabelsIsMutable();
            vertexLabels_.addAll(other.vertexLabels_);
          }
          onChanged();
        }
      } else {
        if (!other.vertexLabels_.isEmpty()) {
          if (vertexLabelsBuilder_.isEmpty()) {
            vertexLabelsBuilder_.dispose();
            vertexLabelsBuilder_ = null;
            vertexLabels_ = other.vertexLabels_;
            bitField0_ = (bitField0_ & ~0x00000001);
            vertexLabelsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVertexLabelsFieldBuilder() : null;
          } else {
            vertexLabelsBuilder_.addAllMessages(other.vertexLabels_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.janusgraph.graphdb.grpc.types.VertexLabel> vertexLabels_ =
      java.util.Collections.emptyList();
    private void ensureVertexLabelsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        vertexLabels_ = new java.util.ArrayList<org.janusgraph.graphdb.grpc.types.VertexLabel>(vertexLabels_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.janusgraph.graphdb.grpc.types.VertexLabel, org.janusgraph.graphdb.grpc.types.VertexLabel.Builder, org.janusgraph.graphdb.grpc.types.VertexLabelOrBuilder> vertexLabelsBuilder_;

    /**
     * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
     */
    public java.util.List<org.janusgraph.graphdb.grpc.types.VertexLabel> getVertexLabelsList() {
      if (vertexLabelsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(vertexLabels_);
      } else {
        return vertexLabelsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
     */
    public int getVertexLabelsCount() {
      if (vertexLabelsBuilder_ == null) {
        return vertexLabels_.size();
      } else {
        return vertexLabelsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
     */
    public org.janusgraph.graphdb.grpc.types.VertexLabel getVertexLabels(int index) {
      if (vertexLabelsBuilder_ == null) {
        return vertexLabels_.get(index);
      } else {
        return vertexLabelsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
     */
    public Builder setVertexLabels(
        int index, org.janusgraph.graphdb.grpc.types.VertexLabel value) {
      if (vertexLabelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVertexLabelsIsMutable();
        vertexLabels_.set(index, value);
        onChanged();
      } else {
        vertexLabelsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
     */
    public Builder setVertexLabels(
        int index, org.janusgraph.graphdb.grpc.types.VertexLabel.Builder builderForValue) {
      if (vertexLabelsBuilder_ == null) {
        ensureVertexLabelsIsMutable();
        vertexLabels_.set(index, builderForValue.build());
        onChanged();
      } else {
        vertexLabelsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
     */
    public Builder addVertexLabels(org.janusgraph.graphdb.grpc.types.VertexLabel value) {
      if (vertexLabelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVertexLabelsIsMutable();
        vertexLabels_.add(value);
        onChanged();
      } else {
        vertexLabelsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
     */
    public Builder addVertexLabels(
        int index, org.janusgraph.graphdb.grpc.types.VertexLabel value) {
      if (vertexLabelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVertexLabelsIsMutable();
        vertexLabels_.add(index, value);
        onChanged();
      } else {
        vertexLabelsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
     */
    public Builder addVertexLabels(
        org.janusgraph.graphdb.grpc.types.VertexLabel.Builder builderForValue) {
      if (vertexLabelsBuilder_ == null) {
        ensureVertexLabelsIsMutable();
        vertexLabels_.add(builderForValue.build());
        onChanged();
      } else {
        vertexLabelsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
     */
    public Builder addVertexLabels(
        int index, org.janusgraph.graphdb.grpc.types.VertexLabel.Builder builderForValue) {
      if (vertexLabelsBuilder_ == null) {
        ensureVertexLabelsIsMutable();
        vertexLabels_.add(index, builderForValue.build());
        onChanged();
      } else {
        vertexLabelsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
     */
    public Builder addAllVertexLabels(
        java.lang.Iterable<? extends org.janusgraph.graphdb.grpc.types.VertexLabel> values) {
      if (vertexLabelsBuilder_ == null) {
        ensureVertexLabelsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, vertexLabels_);
        onChanged();
      } else {
        vertexLabelsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
     */
    public Builder clearVertexLabels() {
      if (vertexLabelsBuilder_ == null) {
        vertexLabels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        vertexLabelsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
     */
    public Builder removeVertexLabels(int index) {
      if (vertexLabelsBuilder_ == null) {
        ensureVertexLabelsIsMutable();
        vertexLabels_.remove(index);
        onChanged();
      } else {
        vertexLabelsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
     */
    public org.janusgraph.graphdb.grpc.types.VertexLabel.Builder getVertexLabelsBuilder(
        int index) {
      return getVertexLabelsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
     */
    public org.janusgraph.graphdb.grpc.types.VertexLabelOrBuilder getVertexLabelsOrBuilder(
        int index) {
      if (vertexLabelsBuilder_ == null) {
        return vertexLabels_.get(index);  } else {
        return vertexLabelsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
     */
    public java.util.List<? extends org.janusgraph.graphdb.grpc.types.VertexLabelOrBuilder> 
         getVertexLabelsOrBuilderList() {
      if (vertexLabelsBuilder_ != null) {
        return vertexLabelsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(vertexLabels_);
      }
    }
    /**
     * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
     */
    public org.janusgraph.graphdb.grpc.types.VertexLabel.Builder addVertexLabelsBuilder() {
      return getVertexLabelsFieldBuilder().addBuilder(
          org.janusgraph.graphdb.grpc.types.VertexLabel.getDefaultInstance());
    }
    /**
     * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
     */
    public org.janusgraph.graphdb.grpc.types.VertexLabel.Builder addVertexLabelsBuilder(
        int index) {
      return getVertexLabelsFieldBuilder().addBuilder(
          index, org.janusgraph.graphdb.grpc.types.VertexLabel.getDefaultInstance());
    }
    /**
     * <code>repeated .janusgraph.types.v1.VertexLabel vertex_labels = 1 [json_name = "vertexLabels"];</code>
     */
    public java.util.List<org.janusgraph.graphdb.grpc.types.VertexLabel.Builder> 
         getVertexLabelsBuilderList() {
      return getVertexLabelsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.janusgraph.graphdb.grpc.types.VertexLabel, org.janusgraph.graphdb.grpc.types.VertexLabel.Builder, org.janusgraph.graphdb.grpc.types.VertexLabelOrBuilder> 
        getVertexLabelsFieldBuilder() {
      if (vertexLabelsBuilder_ == null) {
        vertexLabelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.janusgraph.graphdb.grpc.types.VertexLabel, org.janusgraph.graphdb.grpc.types.VertexLabel.Builder, org.janusgraph.graphdb.grpc.types.VertexLabelOrBuilder>(
                vertexLabels_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        vertexLabels_ = null;
      }
      return vertexLabelsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:janusgraph.schema.v1.GetVertexLabelsResponse)
  }

  // @@protoc_insertion_point(class_scope:janusgraph.schema.v1.GetVertexLabelsResponse)
  private static final org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse();
  }

  public static org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetVertexLabelsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetVertexLabelsResponse>() {
    @java.lang.Override
    public GetVertexLabelsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetVertexLabelsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetVertexLabelsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetVertexLabelsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.janusgraph.graphdb.grpc.schema.GetVertexLabelsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

