// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: janusgraph/schema/v1/schema_manager.proto

package org.janusgraph.graphdb.grpc.schema;

public final class SchemaManager {
  private SchemaManager() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_janusgraph_schema_v1_GetVertexLabelByNameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_janusgraph_schema_v1_GetVertexLabelByNameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_janusgraph_schema_v1_GetVertexLabelByNameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_janusgraph_schema_v1_GetVertexLabelByNameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_janusgraph_schema_v1_GetVertexLabelsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_janusgraph_schema_v1_GetVertexLabelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_janusgraph_schema_v1_GetVertexLabelsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_janusgraph_schema_v1_GetVertexLabelsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_janusgraph_schema_v1_GetEdgeLabelByNameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_janusgraph_schema_v1_GetEdgeLabelByNameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_janusgraph_schema_v1_GetEdgeLabelByNameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_janusgraph_schema_v1_GetEdgeLabelByNameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_janusgraph_schema_v1_GetEdgeLabelsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_janusgraph_schema_v1_GetEdgeLabelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_janusgraph_schema_v1_GetEdgeLabelsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_janusgraph_schema_v1_GetEdgeLabelsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)janusgraph/schema/v1/schema_manager.pr" +
      "oto\022\024janusgraph.schema.v1\032%janusgraph/ty" +
      "pes/v1/graph_types.proto\032&janusgraph/typ" +
      "es/v1/schema_types.proto\"s\n\033GetVertexLab" +
      "elByNameRequest\022@\n\007context\030\001 \001(\0132&.janus" +
      "graph.types.v1.JanusGraphContextR\007contex" +
      "t\022\022\n\004name\030\002 \001(\tR\004name\"c\n\034GetVertexLabelB" +
      "yNameResponse\022C\n\014vertex_label\030\001 \001(\0132 .ja" +
      "nusgraph.types.v1.VertexLabelR\013vertexLab" +
      "el\"Z\n\026GetVertexLabelsRequest\022@\n\007context\030" +
      "\001 \001(\0132&.janusgraph.types.v1.JanusGraphCo" +
      "ntextR\007context\"`\n\027GetVertexLabelsRespons" +
      "e\022E\n\rvertex_labels\030\001 \003(\0132 .janusgraph.ty" +
      "pes.v1.VertexLabelR\014vertexLabels\"q\n\031GetE" +
      "dgeLabelByNameRequest\022@\n\007context\030\001 \001(\0132&" +
      ".janusgraph.types.v1.JanusGraphContextR\007" +
      "context\022\022\n\004name\030\002 \001(\tR\004name\"[\n\032GetEdgeLa" +
      "belByNameResponse\022=\n\nedge_label\030\001 \001(\0132\036." +
      "janusgraph.types.v1.EdgeLabelR\tedgeLabel" +
      "\"X\n\024GetEdgeLabelsRequest\022@\n\007context\030\001 \001(" +
      "\0132&.janusgraph.types.v1.JanusGraphContex" +
      "tR\007context\"X\n\025GetEdgeLabelsResponse\022?\n\013e" +
      "dge_labels\030\001 \003(\0132\036.janusgraph.types.v1.E" +
      "dgeLabelR\nedgeLabels2\350\003\n\024SchemaManagerSe" +
      "rvice\022}\n\024GetVertexLabelByName\0221.janusgra" +
      "ph.schema.v1.GetVertexLabelByNameRequest" +
      "\0322.janusgraph.schema.v1.GetVertexLabelBy" +
      "NameResponse\022n\n\017GetVertexLabels\022,.janusg" +
      "raph.schema.v1.GetVertexLabelsRequest\032-." +
      "janusgraph.schema.v1.GetVertexLabelsResp" +
      "onse\022w\n\022GetEdgeLabelByName\022/.janusgraph." +
      "schema.v1.GetEdgeLabelByNameRequest\0320.ja" +
      "nusgraph.schema.v1.GetEdgeLabelByNameRes" +
      "ponse\022h\n\rGetEdgeLabels\022*.janusgraph.sche" +
      "ma.v1.GetEdgeLabelsRequest\032+.janusgraph." +
      "schema.v1.GetEdgeLabelsResponseB&\n\"org.j" +
      "anusgraph.graphdb.grpc.schemaP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.janusgraph.graphdb.grpc.types.GraphTypes.getDescriptor(),
          org.janusgraph.graphdb.grpc.types.SchemaTypes.getDescriptor(),
        });
    internal_static_janusgraph_schema_v1_GetVertexLabelByNameRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_janusgraph_schema_v1_GetVertexLabelByNameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_janusgraph_schema_v1_GetVertexLabelByNameRequest_descriptor,
        new java.lang.String[] { "Context", "Name", });
    internal_static_janusgraph_schema_v1_GetVertexLabelByNameResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_janusgraph_schema_v1_GetVertexLabelByNameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_janusgraph_schema_v1_GetVertexLabelByNameResponse_descriptor,
        new java.lang.String[] { "VertexLabel", });
    internal_static_janusgraph_schema_v1_GetVertexLabelsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_janusgraph_schema_v1_GetVertexLabelsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_janusgraph_schema_v1_GetVertexLabelsRequest_descriptor,
        new java.lang.String[] { "Context", });
    internal_static_janusgraph_schema_v1_GetVertexLabelsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_janusgraph_schema_v1_GetVertexLabelsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_janusgraph_schema_v1_GetVertexLabelsResponse_descriptor,
        new java.lang.String[] { "VertexLabels", });
    internal_static_janusgraph_schema_v1_GetEdgeLabelByNameRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_janusgraph_schema_v1_GetEdgeLabelByNameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_janusgraph_schema_v1_GetEdgeLabelByNameRequest_descriptor,
        new java.lang.String[] { "Context", "Name", });
    internal_static_janusgraph_schema_v1_GetEdgeLabelByNameResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_janusgraph_schema_v1_GetEdgeLabelByNameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_janusgraph_schema_v1_GetEdgeLabelByNameResponse_descriptor,
        new java.lang.String[] { "EdgeLabel", });
    internal_static_janusgraph_schema_v1_GetEdgeLabelsRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_janusgraph_schema_v1_GetEdgeLabelsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_janusgraph_schema_v1_GetEdgeLabelsRequest_descriptor,
        new java.lang.String[] { "Context", });
    internal_static_janusgraph_schema_v1_GetEdgeLabelsResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_janusgraph_schema_v1_GetEdgeLabelsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_janusgraph_schema_v1_GetEdgeLabelsResponse_descriptor,
        new java.lang.String[] { "EdgeLabels", });
    org.janusgraph.graphdb.grpc.types.GraphTypes.getDescriptor();
    org.janusgraph.graphdb.grpc.types.SchemaTypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
